version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
    - libsndfile1
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install -e ".[docs,metrics-ner,nlstruct,srt-io-converter,webrtc-voice-detector]"
    pre_build:
      - jupyter-book config sphinx docs/
