name: release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  # Adapted from <https://docs.pypi.org/trusted-publishers/using-a-publisher/>
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: build
        run: pipx run build
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1

  # Adapted from <https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions>
  build-docs:
    uses: './.github/workflows/docs.yaml'

  publish-docs:
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4
